module.exports = {
  next_daily_schedule_class: {
    index: 1,
    lecturer_name: "Đoàn Thị Lê Oanh",
    lecturer_avatar:
      "https://r73troypb4obj.vcdn.cloud/user/profile/avatar/71/06132021/1623597375668.png",
    lecturer_display_name: "Đ.T.Lê Oanh",
    assistant_name: "Trần Bích Ngọc",
    assistant_user_name: "ngocttb",
    assistant_display_name: null,
    assistant_id: 75,
    live_assistant_id: null,
    assistant_avatar:
      "https://r73troypb4obj.vcdn.cloud/user/profile/avatar/75/06142021/1623605833201.png",
    get_class_id: null,
    get_class_code: null,
    get_teacher_id: 228439,
    get_teacher_username: "lamqtg",
    get_teacher_full_name: "LamQTG",
    get_teacher_display_name: "LamQTG",
    get_teacher_avatar: null,
    class_name: "Phong_TestTp10_C2",
    class_id: 15423,
    class_code: "Phong_TestTp10_C2",
    learning_class_code: "2S_9EX_21955_51955_1",
    learning_class_training_type_id: 3,
    room_code: null,
    live_at: Date.now(),
    video_url: "https://vimeo.com/444143445",
    video_backup_url: "",
    video_second_backup_url: null,
    video_replay_url: null,
    meeting_join_url:
      "https://us06web.zoom.us/j/89968742538?pwd=VVl0RVI1VFFSdm5FdFpFc0VoQnRKdz09",
    countdown_before: 120,
    late_come_allowed: null,
    live_duration: 1800,
    coach_live_time: 0,
    rating_time: 0,
    battle_waiting_time: 0,
    sound_volume: 20,
    has_test_battle: null,
    test_battle_duration: 278,
    grade_id: 13,
    subject_id: 43,
    learning_object_id: 36952,
    streaming_type: "RTS2",
    sid: "04cd0d6e-e7e6-4e35-b286-2ba4a892",
    streaming_password: null,
    streaming_id: null,
    streaming_api_key: null,
    streaming_api_secret: null,
    streaming_api_account: null,
    learning_object_type: "classLO",
    dsc_xchangeable_points: [
      {
        points_added: 20,
        xchangeable_point_id: "CN",
      },
    ],
    time_before_display: 28800,
    app_settings: [
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_ANSWER_IN_BATTLE",
        attribute_value: "10",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_BATTLE_TOP_1",
        attribute_value: "20",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_BATTLE_TOP_2",
        attribute_value: "15",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_BATTLE_TOP_3",
        attribute_value: "10",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_COMMENT_IN_STREAM",
        attribute_value: "10",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_DEFAULT",
        attribute_value: "CN",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "EXCHANGEABLE_POINT_LIVE_QUIZ_IN_STREAM",
        attribute_value: "10",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "INTERVAL_CHECK_NETWORK_DOWNLOAD_SIZE",
        attribute_value: "10937",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "INTERVAL_CHECK_NETWORK_DOWNLOAD_SPEED_MINIMUM",
        attribute_value: "5",
      },
      {
        entity_name: "MIKAI_LMS_WEB",
        attribute: "INTERVAL_CHECK_NETWORK_DOWNLOAD_URL",
        attribute_value:
          "https://d1xi90fru4wqli.cloudfront.net/picture/others/ktkt.png",
      },
    ],
    slide_urls: ["https://r73troypb4obj.vcdn.cloud/slide/1672029817550"],
    live_quizzes: [
      {
        id: 23458,
        ordering: 1,
        quiz: {
          id: 452274,
          content:
            "<p>Dùng công thức nghiệm để giải phương trình $6x^2 + x - 5 = 0$</p>",
          explanation:
            "<p><b>1. Phân tích gợi ý</b></p><p>Đối với phương trình $ax^2 + bx + c$ = 0 (a ≠ 0) và biệt thức △ = $b^2 - 4ac$</p><p>+ Nếu △ &gt; 0 thì phương trình có hai nghiệm phân biệt \r</p><p>$x_1 = \\frac{-b + \\sqrt△}{2a}$ ; $x_2 = \\frac{-b - \\sqrt△}{2a}$</p><p>+ Nếu △ = 0 thì phương trình có nghiệm kép $x_1 = x_2 = \\frac{-b}{2a}$</p><p>+ Nếu △ &lt; 0 thì phương trình vô nghiệm</p><p><b>2. Bài giải</b></p><p>$△ = 1^2 - 4 \\cdot 6 \\cdot (-5) = 121$</p><p>⇒ △ &gt; 0</p><p>Phương trình có hai nghiệm phân biệt:</p><p>$x_1 = \\frac{-1 + \\sqrt{121}}{2\\cdot6} = \\frac{5}{6}$</p><p>$x_2 = \\frac{-1 - \\sqrt{121}}{2\\cdot6} = -1$</p><p><br></p><p><b>Vậy phương trình đã cho có hai nghiệm phân biệt x = $-1$ và x = $\\frac{5}{6}$.</b></p>",
          quiz_code: "L4_2196_32G-C452274",
          quiz_difficulty_id: null,
          quiz_type_id: 3,
          expected_complete_time: 40,
          quiz_type: {
            id: 3,
            quiz_type_name: "Trắc nghiệm (Multiple choices)",
            has_answer: true,
            has_possible_options: true,
            has_inline_components: false,
            has_ordering: false,
          },
          quiz_possible_options: [
            {
              id: 1848907,
              option_group: "",
              option_code: "B",
              option_value: "<p>x = $-1$, x = $\\frac{-5}{6}$</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848905,
              option_group: "",
              option_code: "C",
              option_value: "<p>x = $-1$, x = $\\frac{5}{6}$</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848908,
              option_group: "",
              option_code: "A",
              option_value: "<p>x = 1, x = $\\frac{5}{6}$</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848906,
              option_group: "",
              option_code: "D",
              option_value: "<p>x = 1, x = $\\frac{-5}{6}$</p>",
              is_in_statement: false,
              published: true,
            },
          ],
          quiz_suggestion: [
            {
              id: 306254,
              suggest:
                "<p>Đối với phương trình $ax^2 + bx + c$ = 0 (a ≠ 0) và biệt thức △ = $b^2 - 4ac$\r</p><p>+ Nếu △ &gt; 0 thì phương trình có hai nghiệm phân biệt\r</p><p>$x_1 = \\frac{-b + \\sqrt△}{2a}$ ; $x_2 = \\frac{-b - \\sqrt△}{2a}$\r</p><p>+ Nếu △ = 0 thì phương trình có nghiệm kép $x_1 = x_2 = \\frac{-b}{2a}$\r</p><p>+ Nếu △ &lt; 0 thì phương trình vô nghiệm</p><p>\r</p><p>\r</p><p>\r</p><p>\r</p>",
            },
          ],
          quiz_answers: {
            possible_option_id: 1848905,
            option_value: "<p>x = $-1$, x = $\\frac{5}{6}$</p>",
            option_code: "C",
          },
          learning_object_id: null,
          learning_object: null,
          generate_index: null,
          reward_info: null,
          created_by_likan_id: 59425,
          updated_by_likan_id: 59425,
          created_at: 1672196800000,
          updated_at: 1672196805000,
          success_rate: null,
          target_rate: null,
          total_quiz: null,
          history_results: null,
          dsc_id: null,
          group: null,
        },
      },
      {
        id: 23459,
        ordering: 2,
        quiz: {
          id: 452272,
          content:
            '<p>Quan sát hình sau và cho biết có bao nhiêu cặp đường thẳng song song?</p><p><img src="https://r73troypb4obj.vcdn.cloud/picture/Quiz%20image/1672061467768.png" style="width: 100%;"><br></p>',
          explanation:
            "<p><b>1. Phân tích gợi ý</b></p><p>Hai đường thẳng a và b không có điểm chung nào, ta nói chúng song song với nhau. Ta viết a // b hoặc b // a.</p><p><b>2. Bài giải</b></p><p>Quan sát hình, ta thấy:</p><p>Hai đường thẳng a và b song song với nhau. Viết là a // b.</p><p>Hai đường thẳng b và c song song với nhau. Viết là b // c.</p><p>Hai đường thẳng a và c song song với nhau. Viết là a // c.</p><p><br></p><p><b>Vậy trong hình có hai cặp đường thẳng song song.</b></p>",
          quiz_code: "L4_41220_7G-C452272",
          quiz_difficulty_id: null,
          quiz_type_id: 3,
          expected_complete_time: 60,
          quiz_type: {
            id: 3,
            quiz_type_name: "Trắc nghiệm (Multiple choices)",
            has_answer: true,
            has_possible_options: true,
            has_inline_components: false,
            has_ordering: false,
          },
          quiz_possible_options: [
            {
              id: 1848900,
              option_group: "",
              option_code: "A",
              option_value: "<p>1</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848898,
              option_group: "",
              option_code: "C",
              option_value: "<p>3</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848897,
              option_group: "",
              option_code: "D",
              option_value: "<p>4</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848899,
              option_group: "",
              option_code: "B",
              option_value: "<p>2</p>",
              is_in_statement: false,
              published: true,
            },
          ],
          quiz_suggestion: [
            {
              id: 306252,
              suggest:
                "<p>Hai đường thẳng a và b không có điểm chung nào, ta nói chúng song song với nhau. Ta viết a // b hoặc b // a.</p>",
            },
          ],
          quiz_answers: {
            possible_option_id: 1848898,
            option_value: "<p>3</p>",
            option_code: "C",
          },
          learning_object_id: null,
          learning_object: null,
          generate_index: null,
          reward_info: null,
          created_by_likan_id: 63410,
          updated_by_likan_id: 63410,
          created_at: 1672194563000,
          updated_at: 1672196665000,
          success_rate: null,
          target_rate: null,
          total_quiz: null,
          history_results: null,
          dsc_id: null,
          group: null,
        },
      },
      {
        id: 23460,
        ordering: 3,
        quiz: {
          id: 452270,
          content:
            '<p>Quan sát hình sau và cho biết có bao nhiêu cặp đường thẳng song song?</p><p><img src="https://r73troypb4obj.vcdn.cloud/picture/Quiz%20image/1672061467768.png" style="width: 100%;"><br></p>',
          explanation:
            "<p><b>1. Phân tích gợi ý</b></p><p>Hai đường thẳng a và b không có điểm chung nào, ta nói chúng song song với nhau. Ta viết a // b hoặc b // a.</p><p><b>2. Bài giải</b></p><p>Quan sát hình, ta thấy:</p><p>Hai đường thẳng a và b song song với nhau. Viết là a // b.</p><p>Hai đường thẳng c và d song song với nhau. Viết là c // d.</p><p>Hai đường thẳng c và e song song với nhau. Viết là c // e.</p><p>Hai đường thẳng d và e song song với nhau. Viết là d // e.</p><p><br></p><p><b>Vậy trong hình có bốn cặp đường thẳng song song.</b></p>",
          quiz_code: "L4_41220_7G-C452270",
          quiz_difficulty_id: null,
          quiz_type_id: 3,
          expected_complete_time: 60,
          quiz_type: {
            id: 3,
            quiz_type_name: "Trắc nghiệm (Multiple choices)",
            has_answer: true,
            has_possible_options: true,
            has_inline_components: false,
            has_ordering: false,
          },
          quiz_possible_options: [
            {
              id: 1848892,
              option_group: "",
              option_code: "A",
              option_value: "<p>1</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848890,
              option_group: "",
              option_code: "C",
              option_value: "<p>3</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848889,
              option_group: "",
              option_code: "D",
              option_value: "<p>4</p>",
              is_in_statement: false,
              published: true,
            },
            {
              id: 1848891,
              option_group: "",
              option_code: "B",
              option_value: "<p>2</p>",
              is_in_statement: false,
              published: true,
            },
          ],
          quiz_suggestion: [
            {
              id: 306250,
              suggest:
                "<p>Hai đường thẳng a và b không có điểm chung nào, ta nói chúng song song với nhau. Ta viết a // b hoặc b // a.</p>",
            },
          ],
          quiz_answers: {
            possible_option_id: 1848889,
            option_value: "<p>4</p>",
            option_code: "D",
          },
          learning_object_id: null,
          learning_object: null,
          generate_index: null,
          reward_info: null,
          created_by_likan_id: 63410,
          updated_by_likan_id: 63410,
          created_at: 1672194335000,
          updated_at: 1672194455000,
          success_rate: null,
          target_rate: null,
          total_quiz: null,
          history_results: null,
          dsc_id: null,
          group: null,
        },
      },
    ],
    countdown_time_teacher: null,
    training_type_id: 3,
    get_duration: 3600,
    get_session_group_id: 4926,
    get_session_group_code: "9MTC2_5_1955_GET_1",
  },
  previous_daily_schedule_class: null,
  after_next: null,
};
