module.exports = {
  parent: null,
  student_id: 54421,
  amount_of_chestnut: 9323,
  amount_of_star: 617,
  amount_of_xp: 96285,
  default_grade_subject: {
    id: null,
    username: null,
    fullname: null,
    phone: null,
    notes: null,
    status: "ACTIVE",
    is_suspended: null,
    suspended_at: null,
    student_id: null,
    grade_id: 12,
    grade_name: "Khối 8",
    grade_original_name: "Khối 8",
    subject_id: 1,
    subject_name: "Môn Toán",
    subject_img_url: "https://r73troypb4obj.vcdn.cloud/web/icon/Toan-Icon.svg",
    product_id: 8,
    is_default: 1,
    package_info: null,
    class_info: {
      id: 13005,
      class_code: "2S_8MPC1_37_1925_1",
      class_name: "Lớp 8 môn toán plus 2 buổi C1 31925 71925 1",
      grade_id: 12,
      subject_id: 1,
      primary_teacher_id: 5364,
      backup_teacher_id: 5364,
      primary_teacher: "huongnt",
      primary_teacher_full_name: "Nguyễn Thị Hương",
      primary_teacher_avatar:
        "https://r73troypb4obj.vcdn.cloud/user/profile/avatar/5364/06282021/1624854938325.png",
      backup_teacher: null,
      max_active_students: 12,
      notes: "Init class for AUS",
      class_days: "3,7",
      class_type: 2,
      class_level: "C1",
      training_type_id: 5,
      current_active_students: null,
      learning_schedules: [
        {
          id: 13,
          class_day: 7,
          live_at: "19:25",
          schedule_code: "7-1925",
        },
        {
          id: 9,
          class_day: 3,
          live_at: "19:25",
          schedule_code: "3-1925",
        },
      ],
    },
    class_student_info: null,
    start_date: 1653930000000,
    end_date: 1685984399999,
    sustenance_start_date: null,
    sustenance_end_date: null,
  },
  first_start_date: 1640019600000,
};
